---
- name: Common setup for all instances
  hosts: all
  become: yes
  roles:
    - common
    - docker

- name: Deploy Redis service
  hosts: redis_group
  become: yes
  roles:
    - redis

- name: Deploy PostgreSQL database
  hosts: postgres_group
  become: yes
  roles:
    - postgres

- name: Deploy Worker backend
  hosts: worker_group
  become: yes
  roles:
    - worker

- name: Deploy Vote frontend
  hosts: vote_group
  become: yes
  roles:
    - vote

- name: Deploy Result frontend
  hosts: result_group
  become: yes
  roles:
    - result
